server:
  port: 8181

spring:
  application:
    name: HystrixDashboard

Hystrix:
  dashboard:
    proxy-stream-allow-list: "*"

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost